### ISSUE TITLE
Document generating PDFs from liquid

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#362] opened 2019-01-31 06:46 UTC
> just wondering if PlatformOS had any HTML > PDF functionality (ie providing ability to users to download PDF versions of dynamically generated data, also possibly emailing PDF attachments generated by PlatformOS ).

**Comment by diana-lakatos** [comment] 2019-06-19 12:38
Duplicate of #491 ?

**Comment by pavelloz** [comment] 2019-06-19 13:30
Yes, this is the same feature, ill copy over this description to there so it wont disappear, because it touches on attaching to email as well.

**Closed as completed** 2019-06-19 13:31 UTC
Labels: topic request, P1
